### ISSUE TITLE
[AVM Module Issue]: Character Length - Application Group Name

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-avm-res-desktopvirtualization-applicationgroup#65]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.4

### Description

Remove this validation check against this variable:
![image](https://github.com/user-attachments/assets/6f7b5064-05b5-46c8-80c6-d03bf3fd240b)
The max character limist for applicationGroups is 64 - https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftdesktopvirtualization

**Comment by jensheerin** [comment]
@birdnathan, thank you for raising the issue! Fix applied with PR #66
