### ISSUE TITLE
[AVM Module Issue]:  default_desktop_display_name conditional logic required

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-avm-res-desktopvirtualization-applicationgroup#69]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.5

### Description

Add Condition to following variable to apply only when type = "desktop"

![image](https://github.com/user-attachments/assets/1d7b5d2e-9fa9-4e29-af42-feddf005dab7)

When type is remoteapp its detected as a change which cannot be applied

![image](https://github.com/user-attachments/assets/398b1977-07a4-4870-a10a-324aa4f7d2da)

Variable description is correct but logic is missing:
![image](https://github.com/user-attachments/assets/3e2b9a96-17da-4ef4-99e7-ff5dc7b8a137)

**Comment by jensheerin** [comment]
https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-applicationgroup/pull/70
