### ISSUE TITLE
[AVM Module Issue]: Lowercase Letters Validation - Application Group Name

### ISSUE THREAD

**Issue by birdnathan** [Azure/terraform-azurerm-avm-res-desktopvirtualization-applicationgroup#72]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.5

### Description

Validation on virtual_desktop_application_group_name variable needs amended. Lowercase letters only should <ins>not</ins> be a limitation for applicationGroups - https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftdesktopvirtualization

![image](https://github.com/user-attachments/assets/564e214c-b1b8-494e-a3aa-59cba51cb249)

**Comment by jensheerin** [comment]
Thank you for raising the issue! fixed with #70
